### PR TITLE
Update commands.js

### PR DESCRIPTION
**Pull request by Fl0te**
Added read Floor Heating Status from DLP

### CODE REVIEW

**Comment by mrgadget** [comment]
Looks fine to me - do you have any more to add? ie - shall I leave this open or merge it?

**Comment by Fl0te** [comment]
Hmmz not sure how this got to you already, new to github and java. Tried to copy the changes you made on the outdoor sensor to floor sensor and 12i1 but only put it in to the fork i made and ask you when i am done with the rest. anyways have tested the two functions and they work for me. Still want to add a few more functions AC control(0x193A) and ac control feedback(0x193B) so working on the feedback for that now. Will need a few days atleast before i am ready. So you can just leave it open

**Comment by mrgadget** [comment]
Well that makes two of us (new to github publishing/forking etc).  I think when you commited it created a pull request perhaps? Who knows.  Anyway, keen to add the extra stuff in anway, so keep adding and committing and I'll merge this in when you're done.

**Comment by Fl0te** [comment]
Should be good to merge it now. Still investegating on Sensors in one(0x1605). I think there is a typo in the document used when writing encoder and parser for it. I have the outdoor sensor (HDL-MSOUT.4W) and Temp. Humidity and Lux Sensor (SB-CMS-THL) and both have values in the wrong places when decoded. Think i have to create a issue at the caligo-mentis/smart-bus to check if it has been tested on other sensors before i change it. 

PS. Have you seen this file i find it more useful than the one you send a grab from.
`http://www.hdlautomation.ca/file-download/hdl-bus-pro-operation-codeseng-jan-08-2013-pdf/`

**Comment by mrgadget** [comment]
That file is much nicer and provides better explainations - but! 0x1605 is interesting.  The document I took a snip of shows Humidity as 1 byte after the 2-byte brightness (your document is missing humidity), which, looking at your data, aligns with your response.  Was it dark when you captured that data (in the issue on my hdl repo)?  Looks like brightness was 00 00, followed by 59 - which would be Humidity - because Air quality can only be 0-3.

So I think try adding humidity like this - other lines have to change because it pushes the other bytes along one:         
```js
  // 12.4.2 Response Read Sensors Status
  0x1605: {
    parse: function(buffer) {
      var data = {
        success: status.parse(buffer, 0),
        temperature: buffer.readUInt8(1) - 20,
        brightness: word.parse(buffer, 2),
        humidity: buffer.readUInt8(4),
        air: buffer.readUInt8(5),
        gas: buffer.readUInt8(6),
        movement: Boolean(buffer.readUInt8(7)),
        dryContacts: []
      };

      var offset = 8;
      var length = buffer.length;
      var contacts = data.dryContacts;

      while (offset < 10 && offset < length) contacts[contacts.length] = {
        number: contacts.length + 1,
        status: Boolean(buffer.readUInt8(offset++))
      };

      return data;
    },

    encode: function(data) {
      var buffer = new Buffer(10);
      var contacts = data.dryContacts || [];

      status.encode(buffer, data.success, 0);
      buffer.writeUInt8(data.temperature + 20, 1);
      word.encode(buffer, data.brightness, 2);
      buffer.writeUInt8(data.humidity, 4);
      buffer.writeUInt8(data.air, 5);
      buffer.writeUInt8(data.gas, 6);
      buffer.writeUInt8(data.movement, 7);

      for (var i = 0; i < contacts.length; i++)
        buffer.writeUInt8(contacts[i].status ? 1 : 0, i + 8);

      return buffer;
    }
  },
```
Give it a shot!

**Comment by Fl0te** [comment]
Yes have noticed the difference myself, got confused thinking gas was humidity in my sensors, but the way you fixed it works. All the values are in the correct place now. Have also tested the dry contacts on the Humidity sensor and they work.
Outdoor Sensor:
outdoor test 1
outdoor test 2
Humidity Sensor:
humi test 1
humi test 2

As you can see the temprature for the humidity sensor is correct. But if i want the outdoor sensor to be correct i need to remove the -20 and + 20 from the code. 

Have tryed to study the "smart-bus" code to understand if the "Device code" is stored someplace. (outdoor sensor 14A. Humidity sensor 136) 
decoder


Was thinking i could check the device code and make a seperate parse and encode for the temprature but have not had success yet. 

Not realy a big problem becouse it is easy to add the 20 deg in Node-Red. But do you know if what i am describing is easy doable or if the "smart-bus" code needs to be completely rewritten?

**Comment by mrgadget** [comment]
At present the required hex isn't passed to the parser/encoder so it would be a reasonable change and I'm not sure it warrants deviating from the main branch that much?

One idea I had is we could create a sensor node in the Node Red side that allows you to choose type from a dropdown, and do the relevant calculations in the background.

Thoughts?

**Comment by Fl0te** [comment]
Ahh ok tought it would be possible to call it without having it in the parser/encoder. I to dont think it is worth it to change the .parser/encoder as this would make changing the whole commands.js necessary.

No need to create a seperate node just complicates it. I just subtract it in a function node.

**Comment by mrgadget** [comment]
@Fl0te was I waiting for you to add/change 0x1605 or something? If not, I'll get this merged.

**Comment by Fl0te** [comment]
Sorry tought it was already changed. 1605 worked great for me with your sugjestion above. I dont have axes to my computer at the moment, so if you can change it i would appreciate it.

**Comment by mrgadget** [comment]
Finally got around to updating that 0x1605 code and pushing it to your branch, then merging it.  Will update the npm package soon.

**Comment by mrgadget** [comment]
Hey - 0.5.3 published to npm incorporating your changes.  Cheers, Ben.

**Pull request merged**
